apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-java-demo
spec:
  replicas: REPLICAS
  selector:
    matchLabels:
      project: www
      app: tomcat-java-demo
  template:
    metadata:
      labels:
        project: www
        app: tomcat-java-demo
    spec:
      imagePullSecrets:
      - name: SECRET_NAME
      containers:
      - image: IMAGE_NAME
        name: tomcat-java-demo
        resources:
          requests:
            cpu: 0.5
            memory: 500Mi
          limits: 
            cpu: 1
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-java-demo 
spec:
  selector:
    project: www
    app: tomcat-java-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
